//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: BaseData.proto
namespace Protobuf.Data
{
  [global::ProtoBuf.ProtoContract(Name=@"BoolData")]
  public partial class BoolData : global::ProtoBuf.IExtensible
  {
    public BoolData() {}
    
    private bool? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Value
    {
      get { return _value?? (bool)true; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (bool?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"DoubleData")]
  public partial class DoubleData : global::ProtoBuf.IExtensible
  {
    public DoubleData() {}
    
    private double? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Value
    {
      get { return _value?? (double)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (double?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"FloatData")]
  public partial class FloatData : global::ProtoBuf.IExtensible
  {
    public FloatData() {}
    
    private float? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Value
    {
      get { return _value?? (float)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (float?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Int32Data")]
  public partial class Int32Data : global::ProtoBuf.IExtensible
  {
    public Int32Data() {}
    
    private int? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value
    {
      get { return _value?? (int)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (int?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"UInt32Data")]
  public partial class UInt32Data : global::ProtoBuf.IExtensible
  {
    public UInt32Data() {}
    
    private uint? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Value
    {
      get { return _value?? (uint)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (uint?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Int64Data")]
  public partial class Int64Data : global::ProtoBuf.IExtensible
  {
    public Int64Data() {}
    
    private long? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Value
    {
      get { return _value?? (long)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (long?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"UInt64Data")]
  public partial class UInt64Data : global::ProtoBuf.IExtensible
  {
    public UInt64Data() {}
    
    private ulong? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Value
    {
      get { return _value?? (ulong)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (ulong?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SInt32Data")]
  public partial class SInt32Data : global::ProtoBuf.IExtensible
  {
    public SInt32Data() {}
    
    private int? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Value
    {
      get { return _value?? (int)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (int?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SInt64Data")]
  public partial class SInt64Data : global::ProtoBuf.IExtensible
  {
    public SInt64Data() {}
    
    private long? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long Value
    {
      get { return _value?? (long)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (long?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Fixed32Data")]
  public partial class Fixed32Data : global::ProtoBuf.IExtensible
  {
    public Fixed32Data() {}
    
    private uint? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint Value
    {
      get { return _value?? (uint)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (uint?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"Fixed64Data")]
  public partial class Fixed64Data : global::ProtoBuf.IExtensible
  {
    public Fixed64Data() {}
    
    private ulong? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong Value
    {
      get { return _value?? (ulong)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (ulong?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SFixed32Data")]
  public partial class SFixed32Data : global::ProtoBuf.IExtensible
  {
    public SFixed32Data() {}
    
    private int? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int Value
    {
      get { return _value?? (int)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (int?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SFixed64Data")]
  public partial class SFixed64Data : global::ProtoBuf.IExtensible
  {
    public SFixed64Data() {}
    
    private long? _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long Value
    {
      get { return _value?? (long)0; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (long?)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"StringData")]
  public partial class StringData : global::ProtoBuf.IExtensible
  {
    public StringData() {}
    
    private string _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Value
    {
      get { return _value?? ""; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (string)null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"BytesData")]
  public partial class BytesData : global::ProtoBuf.IExtensible
  {
    public BytesData() {}
    
    private byte[] _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Value
    {
      get { return _value?? null; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ValueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.Value : (byte[])null; }
    }
    private bool ShouldSerializeValue() { return ValueSpecified; }
    private void ResetValue() { ValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}