// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.View
{
    using ResetCore.UGUI;
    
    
    public class TestUIView : UIView
    {
        
        private UnityEngine.GameObject _goTestButton;
        
        private UnityEngine.UI.Image _imgTestButton;
        
        private UnityEngine.UI.Button _btnTestButton;
        
        private UnityEngine.GameObject _goText;
        
        private UnityEngine.UI.Text _txtText;
        
        private UnityEngine.GameObject _goInputField;
        
        private UnityEngine.UI.Image _imgInputField;
        
        private UnityEngine.UI.InputField _inputInputField;
        
        private UnityEngine.GameObject _goResult;
        
        private UnityEngine.UI.Text _txtResult;
        
        public virtual UnityEngine.GameObject goTestButton
        {
            get
            {
                return this._goTestButton;
            }
            set
            {
                this._goTestButton = value;
            }
        }
        
        public virtual UnityEngine.UI.Image imgTestButton
        {
            get
            {
                return this._imgTestButton;
            }
            set
            {
                this._imgTestButton = value;
            }
        }
        
        public virtual UnityEngine.UI.Button btnTestButton
        {
            get
            {
                return this._btnTestButton;
            }
            set
            {
                this._btnTestButton = value;
            }
        }
        
        public virtual UnityEngine.GameObject goText
        {
            get
            {
                return this._goText;
            }
            set
            {
                this._goText = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtText
        {
            get
            {
                return this._txtText;
            }
            set
            {
                this._txtText = value;
            }
        }
        
        public virtual UnityEngine.GameObject goInputField
        {
            get
            {
                return this._goInputField;
            }
            set
            {
                this._goInputField = value;
            }
        }
        
        public virtual UnityEngine.UI.Image imgInputField
        {
            get
            {
                return this._imgInputField;
            }
            set
            {
                this._imgInputField = value;
            }
        }
        
        public virtual UnityEngine.UI.InputField inputInputField
        {
            get
            {
                return this._inputInputField;
            }
            set
            {
                this._inputInputField = value;
            }
        }
        
        public virtual UnityEngine.GameObject goResult
        {
            get
            {
                return this._goResult;
            }
            set
            {
                this._goResult = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtResult
        {
            get
            {
                return this._txtResult;
            }
            set
            {
                this._txtResult = value;
            }
        }
    }
}
