// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.View
{
    using ResetCore.UGUI;
    
    
    public class TestUIView : UIView
    {
        
        private UnityEngine.GameObject _goMoney;
        
        private UnityEngine.UI.Text _txtMoney;
        
        private UnityEngine.GameObject _goInputField;
        
        private UnityEngine.UI.Image _imgInputField;
        
        private UnityEngine.UI.InputField _inputInputField;
        
        public virtual UnityEngine.GameObject goMoney
        {
            get
            {
                return this._goMoney;
            }
            set
            {
                this._goMoney = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtMoney
        {
            get
            {
                return this._txtMoney;
            }
            set
            {
                this._txtMoney = value;
            }
        }
        
        public virtual UnityEngine.GameObject goInputField
        {
            get
            {
                return this._goInputField;
            }
            set
            {
                this._goInputField = value;
            }
        }
        
        public virtual UnityEngine.UI.Image imgInputField
        {
            get
            {
                return this._imgInputField;
            }
            set
            {
                this._imgInputField = value;
            }
        }
        
        public virtual UnityEngine.UI.InputField inputInputField
        {
            get
            {
                return this._inputInputField;
            }
            set
            {
                this._inputInputField = value;
            }
        }
    }
}
