// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Linq;

namespace ResetCore.Data.AutoSerializer
{

    public class TestSerializeData_Serializer : ISerializer<TestSerializeData>
    {
        
        public void ToXElement(XmlElement xElement, string name, TestSerializeData obj)
        {
            var node = xElement.OwnerDocument.CreateElement(name);
            xElement.AppendChild(node);

            ReXmlSerializer.Write(node, "helloInt", obj.helloInt);
        }

        public TestSerializeData ParseXElement(XmlElement xElement, string name)
        {
            return null;
        }
    }
}
