// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.AutoSerializer
{
    using System.Xml;
    
    
    public class TestSerializeData_Serializer : IXmlSerializer<TestSerializeData>
    {
        
        public virtual void Write(System.Xml.XmlElement xElement, string name, TestSerializeData obj)
        {
			var node = xElement.OwnerDocument.CreateElement(name);
			xElement.AppendChild(node);
			ReXmlSerializer.Write(xElement, "helloInt", obj.helloInt);
			CustomSerializer.GetSerializer<TestSerializeData>().Write(xElement, "testData", obj. testData);
        }
        
        public virtual TestSerializeData Read(System.Xml.XmlElement xElement, string name)
        {
            //var node = string.IsNullOrEmpty(name) ? xElement : xElement.SelectSingleNode(name);
            //ReXmlSerializer.ReadAny()
            return null;
        }
    }
}
