//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: Vector3D.proto
namespace Protobuf.Data
{
  [global::ProtoBuf.ProtoContract(Name=@"Vector3DData")]
  public partial class Vector3DData : global::ProtoBuf.IExtensible
  {
    public Vector3DData() {}
    
    private float? _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _x?? (float)0; }
      set { _x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool XSpecified
    {
      get { return this._x != null; }
      set { if (value == (this._x== null)) this._x = value ? this.X : (float?)null; }
    }
    private bool ShouldSerializeX() { return XSpecified; }
    private void ResetX() { XSpecified = false; }
    
    private float? _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _y?? (float)0; }
      set { _y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool YSpecified
    {
      get { return this._y != null; }
      set { if (value == (this._y== null)) this._y = value ? this.Y : (float?)null; }
    }
    private bool ShouldSerializeY() { return YSpecified; }
    private void ResetY() { YSpecified = false; }
    
    private float? _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _z?? (float)0; }
      set { _z = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ZSpecified
    {
      get { return this._z != null; }
      set { if (value == (this._z== null)) this._z = value ? this.Z : (float?)null; }
    }
    private bool ShouldSerializeZ() { return ZSpecified; }
    private void ResetZ() { ZSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}