// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas.Xml
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    public class hhoho : XmlData<hhoho>
    {
        
        public static String fileName = "hhoho";
        
        private string _test;
        
        private int _asd;
        
        private float _sad;
        
        private int _zxc;
        
        public string test
        {
            get
            {
                return this._test;
            }
            set
            {
                this._test = value;
            }
        }
        
        public int asd
        {
            get
            {
                return this._asd;
            }
            set
            {
                this._asd = value;
            }
        }
        
        public float sad
        {
            get
            {
                return this._sad;
            }
            set
            {
                this._sad = value;
            }
        }
        
        public int zxc
        {
            get
            {
                return this._zxc;
            }
            set
            {
                this._zxc = value;
            }
        }
    }
}
