// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas.Xml
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    public class testtable : XmlData<testtable>
    {
        
        public static String fileName = "testtable";
        
        private int _id;
        
        private int _TestData;
        
        private string _TestString;
        
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        public int TestData
        {
            get
            {
                return this._TestData;
            }
            set
            {
                this._TestData = value;
            }
        }
        
        public string TestString
        {
            get
            {
                return this._TestString;
            }
            set
            {
                this._TestString = value;
            }
        }
    }
}
