// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas.Xml
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    public class tpl_pve_level : XmlData<tpl_pve_level>
    {
        
        public static String fileName = "tpl_pve_level";
        
        private int _LevelId;
        
        private int _LimitTime;
        
        public int LevelId
        {
            get
            {
                return this._LevelId;
            }
            set
            {
                this._LevelId = value;
            }
        }
        
        public int LimitTime
        {
            get
            {
                return this._LimitTime;
            }
            set
            {
                this._LimitTime = value;
            }
        }
    }
}
