// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.Binder
{
    using ResetCore.UGUI;
    using ResetCore.Event;
    using ResetCore.UGUI.View;
    using ResetCore.UGUI.Model;
    
    
    public class TestUIBinder : UIBinder
    {
        
        /// Used to bind view and model
        public override void Bind(UIView view, UIModel model)
        {
            // From g-InputField@input->money:string
((TestUIView)view).inputInputField.Bind(((TestUIModel)model).money);
            // From g-Result@txt->money:string
((TestUIView)view).txtResult.Bind(((TestUIModel)model).money).PoolByNum(2).ResetPoolByTime(2);
        }
    }
}
