// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.View
{
    using ResetCore.UGUI;
    
    
    public class TestUIView : UIView
    {
        
        private UnityEngine.GameObject _goMoney;
        
        private UnityEngine.UI.Text _txtMoney;
        
        private UnityEngine.GameObject _goInputField;
        
        private UnityEngine.UI.Image _imgInputField;
        
        private UnityEngine.UI.InputField _inputInputField;
        
        private UnityEngine.GameObject _goMoney1;
        
        private UnityEngine.UI.Text _txtMoney1;
        
        private UnityEngine.GameObject _goMoney2;
        
        private UnityEngine.UI.Text _txtMoney2;
        
        private UnityEngine.GameObject _goMoney3;
        
        private UnityEngine.UI.Text _txtMoney3;
        
        public virtual UnityEngine.GameObject goMoney
        {
            get
            {
                return this._goMoney;
            }
            set
            {
                this._goMoney = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtMoney
        {
            get
            {
                return this._txtMoney;
            }
            set
            {
                this._txtMoney = value;
            }
        }
        
        public virtual UnityEngine.GameObject goInputField
        {
            get
            {
                return this._goInputField;
            }
            set
            {
                this._goInputField = value;
            }
        }
        
        public virtual UnityEngine.UI.Image imgInputField
        {
            get
            {
                return this._imgInputField;
            }
            set
            {
                this._imgInputField = value;
            }
        }
        
        public virtual UnityEngine.UI.InputField inputInputField
        {
            get
            {
                return this._inputInputField;
            }
            set
            {
                this._inputInputField = value;
            }
        }
        
        public virtual UnityEngine.GameObject goMoney1
        {
            get
            {
                return this._goMoney1;
            }
            set
            {
                this._goMoney1 = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtMoney1
        {
            get
            {
                return this._txtMoney1;
            }
            set
            {
                this._txtMoney1 = value;
            }
        }
        
        public virtual UnityEngine.GameObject goMoney2
        {
            get
            {
                return this._goMoney2;
            }
            set
            {
                this._goMoney2 = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtMoney2
        {
            get
            {
                return this._txtMoney2;
            }
            set
            {
                this._txtMoney2 = value;
            }
        }
        
        public virtual UnityEngine.GameObject goMoney3
        {
            get
            {
                return this._goMoney3;
            }
            set
            {
                this._goMoney3 = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtMoney3
        {
            get
            {
                return this._txtMoney3;
            }
            set
            {
                this._txtMoney3 = value;
            }
        }
    }
}
