// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetObjectJoinUp.proto

public final class NetObjectJoinUp {
  private NetObjectJoinUp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NetObjectJoinUpDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetObjectJoinUpData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 instanceId = 1;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>optional int32 instanceId = 1;</code>
     */
    int getInstanceId();

    /**
     * <code>optional string typeName = 2;</code>
     */
    boolean hasTypeName();
    /**
     * <code>optional string typeName = 2;</code>
     */
    java.lang.String getTypeName();
    /**
     * <code>optional string typeName = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeNameBytes();
  }
  /**
   * Protobuf type {@code NetObjectJoinUpData}
   */
  public  static final class NetObjectJoinUpData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NetObjectJoinUpData)
      NetObjectJoinUpDataOrBuilder {
    // Use NetObjectJoinUpData.newBuilder() to construct.
    private NetObjectJoinUpData(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private NetObjectJoinUpData() {
      instanceId_ = 0;
      typeName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetObjectJoinUpData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              instanceId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              typeName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetObjectJoinUp.internal_static_NetObjectJoinUpData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetObjectJoinUp.internal_static_NetObjectJoinUpData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetObjectJoinUp.NetObjectJoinUpData.class, NetObjectJoinUp.NetObjectJoinUpData.Builder.class);
    }

    private int bitField0_;
    public static final int INSTANCEID_FIELD_NUMBER = 1;
    private int instanceId_;
    /**
     * <code>optional int32 instanceId = 1;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 instanceId = 1;</code>
     */
    public int getInstanceId() {
      return instanceId_;
    }

    public static final int TYPENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object typeName_;
    /**
     * <code>optional string typeName = 2;</code>
     */
    public boolean hasTypeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string typeName = 2;</code>
     */
    public java.lang.String getTypeName() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string typeName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, instanceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeNameBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, instanceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeNameBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetObjectJoinUp.NetObjectJoinUpData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetObjectJoinUp.NetObjectJoinUpData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetObjectJoinUpData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetObjectJoinUpData)
        NetObjectJoinUp.NetObjectJoinUpDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetObjectJoinUp.internal_static_NetObjectJoinUpData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetObjectJoinUp.internal_static_NetObjectJoinUpData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetObjectJoinUp.NetObjectJoinUpData.class, NetObjectJoinUp.NetObjectJoinUpData.Builder.class);
      }

      // Construct using NetObjectJoinUp.NetObjectJoinUpData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        instanceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        typeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetObjectJoinUp.internal_static_NetObjectJoinUpData_descriptor;
      }

      public NetObjectJoinUp.NetObjectJoinUpData getDefaultInstanceForType() {
        return NetObjectJoinUp.NetObjectJoinUpData.getDefaultInstance();
      }

      public NetObjectJoinUp.NetObjectJoinUpData build() {
        NetObjectJoinUp.NetObjectJoinUpData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetObjectJoinUp.NetObjectJoinUpData buildPartial() {
        NetObjectJoinUp.NetObjectJoinUpData result = new NetObjectJoinUp.NetObjectJoinUpData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instanceId_ = instanceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.typeName_ = typeName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetObjectJoinUp.NetObjectJoinUpData) {
          return mergeFrom((NetObjectJoinUp.NetObjectJoinUpData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetObjectJoinUp.NetObjectJoinUpData other) {
        if (other == NetObjectJoinUp.NetObjectJoinUpData.getDefaultInstance()) return this;
        if (other.hasInstanceId()) {
          setInstanceId(other.getInstanceId());
        }
        if (other.hasTypeName()) {
          bitField0_ |= 0x00000002;
          typeName_ = other.typeName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetObjectJoinUp.NetObjectJoinUpData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetObjectJoinUp.NetObjectJoinUpData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int instanceId_ ;
      /**
       * <code>optional int32 instanceId = 1;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 instanceId = 1;</code>
       */
      public int getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>optional int32 instanceId = 1;</code>
       */
      public Builder setInstanceId(int value) {
        bitField0_ |= 0x00000001;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 instanceId = 1;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instanceId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object typeName_ = "";
      /**
       * <code>optional string typeName = 2;</code>
       */
      public boolean hasTypeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string typeName = 2;</code>
       */
      public java.lang.String getTypeName() {
        java.lang.Object ref = typeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            typeName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string typeName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeNameBytes() {
        java.lang.Object ref = typeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string typeName = 2;</code>
       */
      public Builder setTypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string typeName = 2;</code>
       */
      public Builder clearTypeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        typeName_ = getDefaultInstance().getTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string typeName = 2;</code>
       */
      public Builder setTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetObjectJoinUpData)
    }

    // @@protoc_insertion_point(class_scope:NetObjectJoinUpData)
    private static final NetObjectJoinUp.NetObjectJoinUpData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetObjectJoinUp.NetObjectJoinUpData();
    }

    public static NetObjectJoinUp.NetObjectJoinUpData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<NetObjectJoinUpData> PARSER =
        new com.google.protobuf.AbstractParser<NetObjectJoinUpData>() {
      public NetObjectJoinUpData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new NetObjectJoinUpData(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<NetObjectJoinUpData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetObjectJoinUpData> getParserForType() {
      return PARSER;
    }

    public NetObjectJoinUp.NetObjectJoinUpData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetObjectJoinUpData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetObjectJoinUpData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025NetObjectJoinUp.proto\";\n\023NetObjectJoin" +
      "UpData\022\022\n\ninstanceId\030\001 \001(\005\022\020\n\010typeName\030\002" +
      " \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NetObjectJoinUpData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetObjectJoinUpData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NetObjectJoinUpData_descriptor,
        new java.lang.String[] { "InstanceId", "TypeName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
