// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetPostUtil.proto

public final class NetPostUtil {
  private NetPostUtil() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegistDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegistData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string loginChannel = 1;</code>
     */
    boolean hasLoginChannel();
    /**
     * <code>optional string loginChannel = 1;</code>
     */
    java.lang.String getLoginChannel();
    /**
     * <code>optional string loginChannel = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoginChannelBytes();

    /**
     * <code>optional string logoutChannel = 2;</code>
     */
    boolean hasLogoutChannel();
    /**
     * <code>optional string logoutChannel = 2;</code>
     */
    java.lang.String getLogoutChannel();
    /**
     * <code>optional string logoutChannel = 2;</code>
     */
    com.google.protobuf.ByteString
        getLogoutChannelBytes();
  }
  /**
   * Protobuf type {@code RegistData}
   */
  public  static final class RegistData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RegistData)
      RegistDataOrBuilder {
    // Use RegistData.newBuilder() to construct.
    private RegistData(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private RegistData() {
      loginChannel_ = "";
      logoutChannel_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegistData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              loginChannel_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              logoutChannel_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetPostUtil.internal_static_RegistData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetPostUtil.internal_static_RegistData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetPostUtil.RegistData.class, NetPostUtil.RegistData.Builder.class);
    }

    private int bitField0_;
    public static final int LOGINCHANNEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object loginChannel_;
    /**
     * <code>optional string loginChannel = 1;</code>
     */
    public boolean hasLoginChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string loginChannel = 1;</code>
     */
    public java.lang.String getLoginChannel() {
      java.lang.Object ref = loginChannel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginChannel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string loginChannel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoginChannelBytes() {
      java.lang.Object ref = loginChannel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGOUTCHANNEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object logoutChannel_;
    /**
     * <code>optional string logoutChannel = 2;</code>
     */
    public boolean hasLogoutChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string logoutChannel = 2;</code>
     */
    public java.lang.String getLogoutChannel() {
      java.lang.Object ref = logoutChannel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logoutChannel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string logoutChannel = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLogoutChannelBytes() {
      java.lang.Object ref = logoutChannel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logoutChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoginChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLogoutChannelBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLoginChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLogoutChannelBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static NetPostUtil.RegistData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetPostUtil.RegistData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetPostUtil.RegistData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetPostUtil.RegistData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetPostUtil.RegistData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetPostUtil.RegistData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetPostUtil.RegistData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetPostUtil.RegistData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetPostUtil.RegistData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetPostUtil.RegistData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetPostUtil.RegistData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegistData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RegistData)
        NetPostUtil.RegistDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetPostUtil.internal_static_RegistData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetPostUtil.internal_static_RegistData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetPostUtil.RegistData.class, NetPostUtil.RegistData.Builder.class);
      }

      // Construct using NetPostUtil.RegistData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        loginChannel_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        logoutChannel_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetPostUtil.internal_static_RegistData_descriptor;
      }

      public NetPostUtil.RegistData getDefaultInstanceForType() {
        return NetPostUtil.RegistData.getDefaultInstance();
      }

      public NetPostUtil.RegistData build() {
        NetPostUtil.RegistData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetPostUtil.RegistData buildPartial() {
        NetPostUtil.RegistData result = new NetPostUtil.RegistData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginChannel_ = loginChannel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logoutChannel_ = logoutChannel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetPostUtil.RegistData) {
          return mergeFrom((NetPostUtil.RegistData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetPostUtil.RegistData other) {
        if (other == NetPostUtil.RegistData.getDefaultInstance()) return this;
        if (other.hasLoginChannel()) {
          bitField0_ |= 0x00000001;
          loginChannel_ = other.loginChannel_;
          onChanged();
        }
        if (other.hasLogoutChannel()) {
          bitField0_ |= 0x00000002;
          logoutChannel_ = other.logoutChannel_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetPostUtil.RegistData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetPostUtil.RegistData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object loginChannel_ = "";
      /**
       * <code>optional string loginChannel = 1;</code>
       */
      public boolean hasLoginChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string loginChannel = 1;</code>
       */
      public java.lang.String getLoginChannel() {
        java.lang.Object ref = loginChannel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginChannel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string loginChannel = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoginChannelBytes() {
        java.lang.Object ref = loginChannel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginChannel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string loginChannel = 1;</code>
       */
      public Builder setLoginChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginChannel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginChannel = 1;</code>
       */
      public Builder clearLoginChannel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginChannel_ = getDefaultInstance().getLoginChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginChannel = 1;</code>
       */
      public Builder setLoginChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginChannel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logoutChannel_ = "";
      /**
       * <code>optional string logoutChannel = 2;</code>
       */
      public boolean hasLogoutChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string logoutChannel = 2;</code>
       */
      public java.lang.String getLogoutChannel() {
        java.lang.Object ref = logoutChannel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            logoutChannel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logoutChannel = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLogoutChannelBytes() {
        java.lang.Object ref = logoutChannel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logoutChannel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logoutChannel = 2;</code>
       */
      public Builder setLogoutChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logoutChannel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logoutChannel = 2;</code>
       */
      public Builder clearLogoutChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logoutChannel_ = getDefaultInstance().getLogoutChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logoutChannel = 2;</code>
       */
      public Builder setLogoutChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logoutChannel_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RegistData)
    }

    // @@protoc_insertion_point(class_scope:RegistData)
    private static final NetPostUtil.RegistData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetPostUtil.RegistData();
    }

    public static NetPostUtil.RegistData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<RegistData> PARSER =
        new com.google.protobuf.AbstractParser<RegistData>() {
      public RegistData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RegistData(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RegistData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegistData> getParserForType() {
      return PARSER;
    }

    public NetPostUtil.RegistData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegistData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021NetPostUtil.proto\"9\n\nRegistData\022\024\n\014log" +
      "inChannel\030\001 \001(\t\022\025\n\rlogoutChannel\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegistData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegistData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RegistData_descriptor,
        new java.lang.String[] { "LoginChannel", "LogoutChannel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
