// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas.Json
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    public class BuffData : JsonData<BuffData>
    {
        
        public static String fileName = "BuffData";
        
        private string _BuffName;
        
        private float _BuffTime;
        
        public string BuffName
        {
            get
            {
                return this._BuffName;
            }
            set
            {
                this._BuffName = value;
            }
        }
        
        public float BuffTime
        {
            get
            {
                return this._BuffTime;
            }
            set
            {
                this._BuffTime = value;
            }
        }
    }
}
