using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace ResetCore.UGUI
{
    public class UIModel
    {
        //前缀
        public static readonly string genableSign = "g-";
        //自定义UIView命名空间
        public static readonly string uiModelNameSpace = "ResetCore.UGUI.Model";
        //UIView储存位置
        public static readonly string uiModelScriptPath = "ResetCore/AutoGenerateData/UGUI/Model";

    }

}
