// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.Model
{
    using ResetCore.UGUI;
    using ResetCore.Event;
    
    
    public class TestUIModel : UIModel
    {
        
        private string testValue;

        public EventProperty<string> money;

        public TestUIModel()
        {
            // From g-InputField@input->money:string
            money = new EventProperty<string>(() => { return testValue; }, (x) => { testValue = x; });
        }

    }
}
