// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.Model
{
    using ResetCore.UGUI;
    using ResetCore.Event;
    
    
    public class TestUIModel : UIModel
    {
        
        private EventProperty<string> _money;
        
        public TestUIModel()
        {
            // From g-Money@txtMoney->money:string
money = new EventProperty<string>();
        }
        
        public virtual EventProperty<string> money
        {
            get
            {
                return this._money;
            }
            set
            {
                this._money = value;
            }
        }
    }
}
